# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jeong-yena <jeong-yena@student.42.fr>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/11 18:54:27 by jeong-yena        #+#    #+#              #
#    Updated: 2022/01/11 19:16:31 by jeong-yena       ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= lib_yejeong

CC			= gcc
CFLAGS		= -Wall -Werror -Wextra
AR			= ar rcs
RM			= rm -f

all : $(NAME)

$(NAME) : $(LIBS)
	make -C ./libft/libft.a
	$(CC) -o
